# Generated by Django 3.2.3 on 2021-09-13 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_event_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cost',
            field=models.CharField(default=100, max_length=120, verbose_name='Cost'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Event Date'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
