# Generated by Django 3.2.3 on 2021-09-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210913_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default=100, upload_to=None),
            preserve_default=False,
        ),
    ]
