# Generated by Django 3.2.3 on 2021-09-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='venue',
        ),
        migrations.AddField(
            model_name='categories',
            name='name',
            field=models.CharField(default=100, max_length=120, verbose_name='Category Name'),
            preserve_default=False,
        ),
    ]
