# Generated by Django 3.2.3 on 2021-09-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
