# Generated by Django 3.2.3 on 2021-09-17 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
    ]
