# Generated by Django 3.2.3 on 2021-09-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_profile_prof_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prof_picture',
            field=models.ImageField(default=100, upload_to='static'),
            preserve_default=False,
        ),
    ]
