# Generated by Django 3.2.3 on 2021-09-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_alter_profile_prof_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prof_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
    ]
