# Generated by Django 3.2.3 on 2021-12-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_profil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyClubUser',
        ),
    ]
