# Generated by Django 3.2.3 on 2021-12-19 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_delete_myclubuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
