# Generated by Django 3.2.3 on 2021-12-23 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0035_profil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name_plural': 'Ogłoszenia'},
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name_plural': 'Profile'},
        ),
    ]
