# Generated by Django 3.2.3 on 2021-09-06 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_event_myclubuser_venue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='vanue',
            new_name='venue',
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
    ]
