# Generated by Django 3.2.3 on 2021-09-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
