# Generated by Django 3.2.3 on 2021-09-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_remove_profile_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default=10, max_length=60),
            preserve_default=False,
        ),
    ]
