# Generated by Django 3.2.3 on 2021-10-21 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0026_alter_profile_prof_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Announcement Name')),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Announcement Date')),
                ('cost', models.CharField(max_length=120, verbose_name='Cost')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static')),
                ('description', models.TextField(blank=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='event',
            name='venue',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='Categorie',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddField(
            model_name='announcement',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.categorie'),
        ),
    ]
