# Generated by Django 3.2.3 on 2021-12-19 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20211211_0146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
